name: Pull request build
on:
  pull_request:

jobs:
  run-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - name: Build
        run: bun run build
        env:
          # NEXT_PUBLIC_DAO_ADDRESS: ${{secrets.DAO_ADDRESS}}
          NEXT_PUBLIC_DAO_ADDRESS: "0x1234567890123456789012345678901234567890"
          NEXT_PUBLIC_MODE_TOKEN_ADDRESS: "0x1234567890123456789012345678901234567890"
          NEXT_PUBLIC_BPT_TOKEN_ADDRESS: "0x1234567890123456789012345678901234567890"
          NEXT_PUBLIC_CHAIN_NAME: sepolia
          NEXT_PUBLIC_WEB3_URL_PREFIX: https://rpc/
          NEXT_PUBLIC_ALCHEMY_API_KEY: x
          NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID: x
          NEXT_PUBLIC_IPFS_ENDPOINT: https://ipfs/
          NEXT_PUBLIC_IPFS_API_KEY: x
          NEXT_PUBLIC_ETHERSCAN_API_KEY: x
          NODE_ENV: production
